name: aemvl_survey_noise
channels:
    - default
dependencies:
  - python=3.6.6
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pip:
    - plotly
    - dash
    - dash_core_components
    - dash_html_components
    - plotly
    #Dev
    - pylint
    - black
  